### ISSUE TITLE
[crossbrowsertesting] manager returned a tunnel ... that was not created by platform

### ISSUE THREAD

**Issue by reeteshranjan** [reeteshranjan/cross-browser-tests-runner#47]
```
Unhandled rejection Error: Platforms.Core.Platform: manager returned a tunnel with pid 4939 tunnel-id cbt-analyzer-crossbrowsertesting that was not created by platform
    at findPlatformTunnel (/home/travis/build/[secure]/cbt-analyzer/node_modules/[secure]/lib/platforms/core/platform.js:269:9)
    at Manager.withId.then.procs (/home/travis/build/[secure]/cbt-analyzer/node_modules/[secure]/lib/platforms/core/platform.js:233:18)
    at tryCatcher (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/travis/build/[secure]/cbt-analyzer/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Traces like this can be seen in jobs that run tests on crossbrowsertesting browsers. For example: https://travis-ci.org/cross-browser-tests-runner/cbt-analyzer/jobs/298030788

This should have never happened in any given build job.

- Is this something to do with Travis environment?
- If not, investigate the cause of this in code.

**Comment by reeteshranjan** [comment]
As theorized earlier, this should never happen. It can be seen that no part of the code causes this. This has something to do with the bugs in crossbrowsertesting tunnels. It can be also seen with the following issues of "too many tunnels with the same name. this should never happen." in jobs like https://travis-ci.org/cross-browser-tests-runner/cbt-analyzer/jobs/298030788 that what is happening post a tunnel dying is that there is some kind of new tunnel process coming up which is not created by us hence the error thrown. Now crossbrowsertesting start complaining that there are too many tunnels with the same name which makes sense, because the documented behavior is that on one given server, only one tunnel process with a given tunnel name exists (the existing gets killed if a new one is started).

Masking this error in our code would re-open the mess this design of not accepting tunnels created outside cross-browser-tests-runner solves. Hence, the error thrown here won't be handled so we can easily trace errors.

A related issue that has been accounted in another bugs is that of not killing server side tunnel instances when a tunnel process dies. It has been seen that when a Travis job runs, a huge bunch of tunnels with the same name can be seen on the crossbrowsertesting app dashboard. As part of solving this another bug, now once we see a tunnel dead we clean up its corresponding server side instance before starting a new one. This fix could help us eliminate a potential cause of what is documented in this issue.
